pipeline {
    agent any
    
    stages {
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/heshanjeewantha/GitHub-Docker-and-Jenkins-CI-CD-Pipeline'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                bat 'docker build -t heshan2000/my-node-app:${BUILD_NUMBER} .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'test-dockerhubpassword', variable: 'test-dockerhubpass')])  {
                    script {  
                        bat "docker login -u heshan2000 -p '${test-dockerhubpass}'"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                bat "docker push heshan2000/my-node-app:${BUILD_NUMBER}"
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
    }
}
